### ISSUE TITLE
Postman desktop app installed via Flatpak crashed when trying to open Run collection > Performance

### ISSUE THREAD

**Issue by artemudovyk** [flathub/com.getpostman.Postman#231]
*My question*:
Installed Postman with Flatpak on Ubuntu 22.04. When I'm trying to open the "Performance" tab in the "Run collection", the app crashes. 
Postman version 10.16.0, the latest version up to date in Flatpak.

*Details (like screenshots)*:

Stack trace:
```
1690454870857 main info "ExecutionSystem execution ~ Sub process terminated with",0
TypeError: Cannot read properties of null (reading 'context')
    at NewRelicTransport.log (/app/extra/Postman/resources/app/node_modules/@postman/app-logger/lib/transports/winston/NewRelicTransport.js:34:23)
    at NewRelicTransport._write (/app/extra/Postman/resources/app/node_modules/winston-transport/index.js:82:19)
    at doWrite (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at NewRelicTransport.Writable.write (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:302:11)
    at DerivedLogger.ondata (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DerivedLogger.emit (node:events:390:28)
    at DerivedLogger.emit (node:domain:475:12)
    at addChunk (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DerivedLogger.Readable.push (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DerivedLogger.Transform.push (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DerivedLogger._transform (/app/extra/Postman/resources/app/node_modules/winston/lib/winston/logger.js:235:12)
    at DerivedLogger.Transform._read (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DerivedLogger.Transform._write (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
1690454870861 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read properties of null (reading 'context')","stack":"TypeError: Cannot read properties of null (reading 'context')\n    at NewRelicTransport.log (/app/extra/Postman/resources/app/node_modules/@postman/app-logger/lib/transports/winston/NewRelicTransport.js:34:23)\n    at NewRelicTransport._write (/app/extra/Postman/resources/app/node_modules/winston-transport/index.js:82:19)\n    at doWrite (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:390:139)\n    at writeOrBuffer (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:381:5)\n    at NewRelicTransport.Writable.write (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:302:11)\n    at DerivedLogger.ondata (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:619:20)\n    at DerivedLogger.emit (node:events:390:28)\n    at DerivedLogger.emit (node:domain:475:12)\n    at addChunk (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:291:12)\n    at readableAddChunk (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:278:11)\n    at DerivedLogger.Readable.push (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:245:10)\n    at DerivedLogger.Transform.push (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:148:32)\n    at DerivedLogger._transform (/app/extra/Postman/resources/app/node_modules/winston/lib/winston/logger.js:235:12)\n    at DerivedLogger.Transform._read (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:184:10)\n    at DerivedLogger.Transform._write (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:172:83)\n    at doWrite (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)"}
Main~handleUncaughtError - Uncaught errors TypeError: Cannot read properties of null (reading 'context')
    at NewRelicTransport.log (/app/extra/Postman/resources/app/node_modules/@postman/app-logger/lib/transports/winston/NewRelicTransport.js:34:23)
    at NewRelicTransport._write (/app/extra/Postman/resources/app/node_modules/winston-transport/index.js:82:19)
    at doWrite (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at NewRelicTransport.Writable.write (/app/extra/Postman/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:302:11)
    at DerivedLogger.ondata (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DerivedLogger.emit (node:events:390:28)
    at DerivedLogger.emit (node:domain:475:12)
    at addChunk (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DerivedLogger.Readable.push (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DerivedLogger.Transform.push (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DerivedLogger._transform (/app/extra/Postman/resources/app/node_modules/winston/lib/winston/logger.js:235:12)
    at DerivedLogger.Transform._read (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DerivedLogger.Transform._write (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/app/extra/Postman/resources/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)

```

*I've already tried*:
Installed Postman with Snap (10.16.3), and no crashes occur in this version. But I'd prefer to use a Flatpak version.

**Comment by ghisvail** [comment]
Is it happening with the latest update?

**Comment by malachibazar** [comment]
It's happening on version `10.19.7` for me with Flatpak on pop os 22.04.

**Comment by ngavrilenkov** [comment]
Find solution here https://github.com/flathub/com.getpostman.Postman/issues/237#issuecomment-1737689928

**Comment by ghisvail** [comment]
Duplicate of #237
