### ISSUE TITLE
Postman does not open

### ISSUE THREAD

**Issue by guilhermesousa-cwi** [flathub/com.getpostman.Postman#237]
Ubuntu 22.04.3 LTS

X11
--------------------------------------------------------------------------

Postman when run via CLI or GUI does not open.

Installed the latest version from the Ubuntu app store. Flathub website is returning 404 page not found.

Via CLI we can see some logs.

flatpak run com.getpostman.Postman                         
The disableGPU setting is set to undefined
Not disabling GPU
Gtk-Message: 12:19:22.829: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:19:22.942: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:19:22.946: Failed to load module "canberra-gtk-module"
[10:0921/121923.009665:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
[10:0921/121923.009772:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Arquivo ou diretório inexistente
Main: Starting cleanup of stale files
Main: Cleanup of stale files completed
ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
/bin/sh: linha 1: xdg-mime: comando não encontrado

LaunchProcess: failed to execvp:
xdg-settings
Main~createDefaultWorkingDir - Default working dir creation already attempted
1695309563229 main info "Booting Postman 10.18.4, linux-6.2.0-33-generic on x64"
1695309563232 main info "EventBus~initialize - Success"
1695309563235 main info "Proxy configuration has not been setup"
1695309563237 main info "CloudProxyManager~init - Success"
1695309563298 main info "performShellDataMigration: Migration has already been done. Bailing out"
1695309563316 main info "UpdateHandler~init - Success"
1695309563320 main info "LeaderSelection: Initialized successfully"
1695309563322 main info "VersionDependencyService: Initialized successfully"
error reading fileError: ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1695309563347 main info "Generated root certificate for linux"
1695309563350 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1695309563392 main info "GPU detected VID 32902 DID 39745 ACTIVE true"
[47:0921/121923.421370:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
1695309563465 main info "shellController~init: Success"
1695309563502 main info "shellMeta~init: Success"
1695309563503 main info "partitionMigrationService: State of V7 partition:"
1695309563504 main info "partitionMigrationService: V7 partitions",[]
1695309563505 main info "partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no partition with scratchpad namespace"
1695309563506 main info "partitionMigrationService~rectifyNamespaceOfScratchPadPartition: There is no transit partition which could have been used for scratchpad"
1695309563506 main info "partitionMigrationService~init: Success"
1695309563573 main info "partitionMigrationService~runV8PartitionsIntegrity: Two way migration~ removing the following partitions from v8",[]
1695309563680 main error "Error encountered while creating root CA",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n    at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n    at ChildProcess.<anonymous> (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n    at ChildProcess.emit (node:events:390:28)\n    at ChildProcess.emit (node:domain:475:12)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Socket.<anonymous> (node:internal/child_process:450:11)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at Pipe.<anonymous> (node:net:687:12)"}
1695309563680 main error "Error generating rootCA certificate for HTTPS proxy",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n    at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n    at ChildProcess.<anonymous> (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n    at ChildProcess.emit (node:events:390:28)\n    at ChildProcess.emit (node:domain:475:12)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Socket.<anonymous> (node:internal/child_process:450:11)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at Pipe.<anonymous> (node:net:687:12)"}
1695309563681 main error "HTTPSProxy~Unable to generate certificates",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/guilherme/.var/app/com.getpostman.Postman/cache/ac7027ce6ef85f21fd7b36a6651478f010abb82c\n4017FEC9EA7F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n    at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n    at ChildProcess.<anonymous> (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n    at ChildProcess.emit (node:events:390:28)\n    at ChildProcess.emit (node:domain:475:12)\n    at maybeClose (node:internal/child_process:1064:16)\n    at Socket.<anonymous> (node:internal/child_process:450:11)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at Pipe.<anonymous> (node:net:687:12)"}
1695309563692 main info "userPartitionService~getRecentV8UserPartition: recent v8 user context partition ","50b2391e-b37c-421f-bd4f-231d2a493541"
1695309563692 main info "userPartitionService~_rectifyTheActivePartitionOfApplication: Setting the active partition to ","50b2391e-b37c-421f-bd4f-231d2a493541"
1695309563719 main info "userPartitionService~init: Success"
1695309563764 main info "userPartitionService: State of v8 partition system:"
1695309563778 main info "shell~init~getPartitionToLoad: loading active partition"
1695309563784 main info "userPartitionService: List of partitions:",[{"partitionId":"50b2391e-b37c-421f-bd4f-231d2a493541","namespace":"users","userId":"21137513","teamId":"1285670","lastUpdated":"2023-09-21T14:20:15.045Z"},{"partitionId":"5a9b379b-1c82-43e0-9e43-9b2c20aeb041","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]
1695309563784 main info "userPartitionService: users global meta:",{}
1695309570805 main info "RuntimeIPCAgent~started: Success"
1695309571502 main info "Main~getRemoteInitPath:: "
1695309571990 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
Error: ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1695309572000 main error "Main~handleUncaughtError - Uncaught errors",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt","name":"Error","message":"ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'","stack":"Error: ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'"}
Main~handleUncaughtError - Uncaught errors [Error: ENOENT: no such file or directory, open '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/guilherme/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
}
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }
1695309572047 main info "windowManager: First requester booted successfully."
1695309572047 main info "windowManager~restoreWindows: Restoring requester windows"
1695309572048 main info "Main~AppEvents - Received booted event for process requester.Version 10.18.5 UI Version: 10.18.5-ui-230920-1358 Desktop Platform Version: 10.18.4"

**Comment by kamenlitchev** [comment]
Same for Fedora 38 / KDE

**Comment by joligoms** [comment]
Same for Fedora 38 Workstation here.

**Comment by anaximeno** [comment]
Many are having this problem.

Refs:
- https://github.com/postmanlabs/postman-app-support/issues/12330
- https://github.com/postmanlabs/postman-app-support/issues/11620

This solution worked for me https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639 you may try it, but this still has to be fixed in the app.

**Comment by LLNet** [comment]
@kamenlitchev it work - thanks for help :-)

**Comment by Klusio19** [comment]
Same problem for latest Debian testing with KDE. Running from icon on dekstop or via cli with `flatpak run com.getpostman.Postman` results in that error ONLY WHEN LOGGED IN.
Running provided OpenSSL command as @kerryhatcher mentioned works.

**Comment by DiracSpace** [comment]
@kerryhatcher your solution worked for me on Ubuntu 23.10, thank you!

**Comment by rokdelak** [comment]
Still broken, I installed popOS on 3 machines in the last 3 months (the last one yesterday) and every time I had to generate the certificates by hand, then it works fine.

**Comment by Liamhhhhh** [comment]
If Postman isn't starting properly, you might want to try using [Apidog](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1) instead. That's what I did, and it worked well for me. 
﻿ 
﻿

**Comment by feliperdamaceno** [comment]
@kerryhatcher this worked for Pop Os 22.04 LTS

**Comment by QazCetelic** [comment]
I also have this issue on openSUSE Tumbleweed 20240704 with KDE Plasma Version: 6.1.2 and Wayland. Overwriting the certificate helped.

**Comment by maxtheaxe** [comment]
> Error confirmed on Pop!_OS 22.04 LTS .
> 
> To see the actual error, run the flatpack from the CLI. Just opening via GUI results in a crash with no details:
> 
> ```shell
> flatpak run com.getpostman.Postman
> ```
> 
> Also as @anaximeno mentioned, running the following OpenSSL command ([found here](https://github.com/postmanlabs/postman-app-support/issues/11620#issuecomment-1727280639)) resolves the problem (post install).
> 
> Note: Slightly modified the file path names from the original to make it easier to copy and paste the command for future visitors here.
> 
> ```shell
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout ~/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.key -out ~/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt
> ```
> 
> What I don't know is if there are in downstream or long term effects of this. Obviously when dealing with certs and security, its best to leave it alone and let smarter people work it out. So This needs to get fixed asap. Willing to help however I can but I don't know anything about flatpack development.

This solved the insta-crashing issue for me, but in case it helps anyone else, I also needed to fully sign out and clear local data, restart the app, and then sign in again to get it working.

**Comment by Jhynn** [comment]
I found a [post](https://brunojesus.pt/posts/20240504_postman_flatpak_fedora40/) which I have success in solving this problem, just follow the steps below, I use arch btw.

1. Go to the directory `~/.var/app/com.getpostman.Postman/config/Postman/proxy`, then.
2. Generate a valid certificate:

`cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy`

`openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt`

**Comment by miguilimzero** [comment]
I'm also facing this issue. Fedora 40 with Wayland.

**Comment by Jhynn** [comment]
@miguilimzero have you tried my answer (the comment above yours)? Please consider executing both of those instructions.

**Comment by ferdnyc** [comment]
While the above _does_ fix this for users experiencing the issue (which is everyone), a **REAL** fix would be to bundle a copy of `openssl` in with the Postman Flatpak, since it requires that command in order to function properly. (Unless there's a Flatpak runtime that it can depend on,  which would provide the `openssl` command instead.)

Either way, the issue is ultimately a problem with the Postman Flatpak definition (the thing _that lives in this repo_), which is failing to package all of the necessary tools.

**Comment by ferdnyc** [comment]
I managed to "trick" Postman into accepting that `openssl` is present in its sandboxed environment by editing the Flatpak definition to monkeypatch one of its `.js` files after installation (immediately before the app launches), and building+installing that locally.

(Apologies for the insanely long line, but the diff on `com.getpostman.Postman.yaml` is...)

```diff
diff --git a/com.getpostman.Postman.yaml b/com.getpostman.Postman.yaml
index 205ebcd..c7606b1 100644
--- a/com.getpostman.Postman.yaml
+++ b/com.getpostman.Postman.yaml
@@ -37,6 +37,7 @@ modules:
           - rm Postman.tar.gz
           - mkdir -p /app/extra/Postman
           - mv Postman/app/* /app/extra/Postman
+          - sed -E -e 's/(if \(process.platform !== .linux.)\)/\1 || process.env.FLATPAK_ID !== undefined)/' /app/extra/Postman/resources/app/services/electronProxy.js > patched_electronProxy.js && mv patched_electronProxy.js /app/extra/Postman/resources/app/services/electronProxy.js
       - type: extra-data
         only-arches:
           - x86_64
```

That will change one line in its `checkOpenSSLInstallation()` function, which (prior to the change) contains:

```js
function checkOpenSSLInstallation () {
  return new Promise((resolve) => {

    /**
     * This check is only required for linux as for other operating systems openssl
     * is not a dependency, since we use node-forge to generate the ssl certificates.
     *
     * Hence we return true for operating systems other than linux
     */
    if (process.platform !== 'linux') return resolve(true);

    which('openssl', function (error) {
      if (error) {
        return resolve(false);
      }
      return resolve(true);
    });
  });
}
```

The problem is that `which` doesn't work inside the Flatpak environment. But we know that `/usr/bin/openssl` will always be there, so the `sed` command just changes the `if()` condition to:

```js
if (process.platform !== 'linux' || process.env.FLATPAK_ID !== undefined)
    return resolve(true);
```

`${FLATPAK_ID}` will always be defined in the environment of a Flatpak sandbox.

...So, that works, and Postman _attempts_ to run `openssl` — but it's still failing, now with unreadably-formatted errors from the `openssl` command attempts themselves. (Apologies for the utter illegibility of what follows...)

```text
error reading fileError: ENOENT: no such file or directory, open '$HOME/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1736220207942 main info "Generated root certificate for linux"
1736220207945 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1736220207960 main info "newAccountRegionPreferenceService~getPreferenceWithFallback - Preference not found in storage."
1736220207960 main info "newAccountRegionPreferenceService~getToggleMenuTemplate - Using preference:","useUSRegion"
1736220207992 main info "userPartitionService~init: Success"
1736220208030 main info "userPartitionService: State of v8 partition system:"
1736220208031 main info "shell~init~getPartitionToLoad: loading active partition"
1736220208031 main info "userPartitionService: List of partitions:",[{"partitionId":"948b3514-d73f-411c-a14a-6d1f766f9a01","namespace":"users","userId":"13321783","teamId":"0","lastUpdated":"2025-01-06T23:18:20.275Z"},{"partitionId":"65721405-8b51-4027-96d5-9460494923e0","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]
1736220208032 main info "userPartitionService: users global meta:",{}
1736220208032 main info "Main:windowManager~newRequesterWindow: Fetch and update runtime config: us"
1736220208228 main error "Error encountered while creating root CA",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key $HOME/.var/app/com.getpostman.Postman/cache/3f600afe39219f4f6fbadcb5d516693cf8dcb5dd\n40770E8E697F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key $HOME/.var/app/com.getpostman.Postman/cache/3f600afe39219f4f6fbadcb5d516693cf8dcb5dd\n40770E8E697F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n    at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n    at ChildProcess.<anonymous> (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n    at ChildProcess.emit (node:events:517:28)\n    at ChildProcess.emit (node:domain:489:12)\n    at maybeClose (node:internal/child_process:1098:16)\n    at Socket.<anonymous> (node:internal/child_process:450:11)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at Pipe.<anonymous> (node:net:350:12)"}
1736220208229 main error "Error generating rootCA certificate for HTTPS proxy",{"name":"Error","message":"Unable to regenerate new certificates","stack":"Error: Unable to regenerate new certificates\n    at Object.ensureRootCAPresence (/app/extra/Postman/resources/app/services/proxyCertificateService.js:182:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /app/extra/Postman/resources/app/services/proxyCertificateService.js:303:22"}
1736220208230 main error "HTTPSProxy~Unable to generate certificates",{"name":"Error","message":"Unable to regenerate new certificates","stack":"Error: Unable to regenerate new certificates\n    at Object.ensureRootCAPresence (/app/extra/Postman/resources/app/services/proxyCertificateService.js:182:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /app/extra/Postman/resources/app/services/proxyCertificateService.js:303:22"}
1736220209280 main info "Main~getRemoteInitPath:: "
1736220209347 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
1736220209353 main info "INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge"
Error: ENOENT: no such file or directory, open '$HOME/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1736220209367 main error "Main~handleUncaughtError - Uncaught errors",{"errno":-2,"code":"ENOENT","syscall":"open","path":"$HOME/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt","name":"Error","message":"ENOENT: no such file or directory, open '$HOME/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'","stack":"Error: ENOENT: no such file or directory, open '$HOME/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'"}
Main~handleUncaughtError - Uncaught errors [Error: ENOENT: no such file or directory, open '$HOME/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '$HOME/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
}
```

So now it's not clear _what_ it's doing wrong. And the code that's failing appears to be stuffed away in `/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js` which actually points inside `/app/extra/Postman/resources/app/node_modules/@postman/pem/dist/index.js`, a minified, not-fit-for-human-consumption JS archive. (There is a source map alongside it, so that's some small favor.)

**Comment by PostboxRetinal** [comment]
> I found a [post](https://brunojesus.pt/posts/20240504_postman_flatpak_fedora40/) which I had success in solving this problem, just follow the steps below, I use arch btw.
> 
>     1. Go to the directory `~/.var/app/com.getpostman.Postman/config/Postman/proxy`, then.
> 
>     2. Generate a valid certificate:
> 
> 
> > Simply just run the below instructions on your terminal.
> 
> cd ~/.var/app/com.getpostman.Postman/config/Postman/proxy
> 
> openssl req -subj '/C=US/CN=Postman Proxy' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout postman-proxy-ca.key -out postman-proxy-ca.crt
> 
> Guys, please execute the instructions above, I believe this is the solution... Let's close this issue (it has probably already been resolved).

Manually querying `openssl` for the certificate solved the issue for flatpak version 11.28.4 on openSUSE Tumbleweed, thanks!
