### ISSUE TITLE
Crashing while login with an external browser

### ISSUE THREAD

**Issue by oscar-besga-panel** [flathub/com.getpostman.Postman#291]
When I click to login with my account, an external browser widow is opened with the postman website, to login within the application. I log in with my user/pass and when it returns to my app, it crashes.
If try to open again, it crashes and autoclose again.
Trying to open from command line, and this is the output message (like a cert file missing?)

```
1734112840689 main info "userPartitionService: List of partitions:",[{"partitionId":"d905d434-2690-43c4-be01-b2043c928619","namespace":"users","userId":"5044174","teamId":"0","lastUpdated":"2024-12-12T09:40:57.447Z"},{"partitionId":"d964611a-6108-4df9-b9da-6f56921027ae","namespace":"scratchPad","userId":0,"teamId":0,"isDirty":false}]
1734112840690 main info "userPartitionService: users global meta:",{}
1734112840690 main info "Main:windowManager~newRequesterWindow: Fetch and update runtime config: us"
1734112840887 main error "Error encountered while creating root CA",{"name":"Error","message":"Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/user/.var/app/com.getpostman.Postman/cache/6bed1af7794aec9bba3752eafc4e6beb2c382b53\n402760BDA87F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n","stack":"Error: Invalid openssl exit code: 1\n% openssl req -new -sha256 -subj /C=US/CN=Postman Proxy CA -key /home/user/.var/app/com.getpostman.Postman/cache/6bed1af7794aec9bba3752eafc4e6beb2c382b53\n402760BDA87F0000:error:03000093:digital envelope routines:default_check:command not supported:../crypto/evp/ctrl_params_translate.c:329:\n\n    at done (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:171:1)\n    at ChildProcess.<anonymous> (/app/extra/Postman/resources/app/node_modules/@postman/pem/webpack:/pem/lib/openssl.js:188:1)\n    at ChildProcess.emit (node:events:517:28)\n    at ChildProcess.emit (node:domain:489:12)\n    at maybeClose (node:internal/child_process:1098:16)\n    at Socket.<anonymous> (node:internal/child_process:450:11)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at Pipe.<anonymous> (node:net:350:12)"}
1734112840889 main error "Error generating rootCA certificate for HTTPS proxy",{"name":"Error","message":"Unable to regenerate new certificates","stack":"Error: Unable to regenerate new certificates\n    at Object.ensureRootCAPresence (/app/extra/Postman/resources/app/services/proxyCertificateService.js:182:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /app/extra/Postman/resources/app/services/proxyCertificateService.js:303:22"}
1734112840889 main error "HTTPSProxy~Unable to generate certificates",{"name":"Error","message":"Unable to regenerate new certificates","stack":"Error: Unable to regenerate new certificates\n    at Object.ensureRootCAPresence (/app/extra/Postman/resources/app/services/proxyCertificateService.js:182:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at /app/extra/Postman/resources/app/services/proxyCertificateService.js:303:22"}
1734112842553 main info "Main~getRemoteInitPath:: "
1734112842622 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
Error: ENOENT: no such file or directory, open '/home/user/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
1734112842637 main error "Main~handleUncaughtError - Uncaught errors",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/user/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt","name":"Error","message":"ENOENT: no such file or directory, open '/home/user/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'","stack":"Error: ENOENT: no such file or directory, open '/home/user/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'"}
Main~handleUncaughtError - Uncaught errors [Error: ENOENT: no such file or directory, open '/home/user/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/.var/app/com.getpostman.Postman/config/Postman/proxy/postman-proxy-ca.crt'
}
1734112842646 main info "INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge"
1734112842672 main info "windowManager: First requester booted successfully."
1734112842672 main info "windowManager~restoreWindows: Restoring requester windows"
1734112842673 main info "Main~AppEvents - Received booted event for process requester.Version 11.22.1 UI Version: 11.22.1-ui-241209-1418 Desktop Platform Version: 11.22.0"
```

**Comment by Remu-rin** [comment]
Duplicate of https://github.com/flathub/com.getpostman.Postman/issues/237
You can find a workaround for manually generating certs.
